drivers:
  elasticsearchv1:
    local:
      domains:
        - http://localhost:9200

  mysql:
    maria:
      host: localhost
      login: guest
      password: guest
      database: test
      port: 3306
      protocol: tcp

  rabbitmq-consumer:
    local:
      uri: amqp://guest:guest@localhost:5672/
      exchange: default-exchange
      exchangeType: direct
      queue: default-queue
      bindingKey: default-key
      consumerTag: simple-consumer

  rabbitmq-producer:
    local:
      uri: amqp://guest:guest@localhost:5672/
      exchange: default-exchange
      exchangeType: direct
      routingKey: default-key
      producerTag: simple-consumer
      reliable: true

